---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: creator

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: creator
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: creator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: creator
subjects:
- kind: ServiceAccount
  namespace: default
  name: creator


